name: CI

on:
    push:
        branches: [ master ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
            -   name: Build with Maven
                run: mvn --batch-mode --update-snapshots verify
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v2
                with:
                    fail_ci_if_error: true
                    token: 5b98df4a-0d60-4dd2-882d-eacd698b3c27
